### ISSUE TITLE
Why the project stalled?

### ISSUE THREAD

**Issue by mkpankov** [ckkashyap/unix#8]
Hi,

Sorry to create an issue about this, but I'm very interested in why you decided to abandon Rust for this task and use Nim instead.

Could you please tell us what are the challenges and why Rust is poorly suited to deal with them?

**Comment by ckkashyap** [comment]
Sorry ... I missed this note from you.

IMO ... its not that Rust is poorly suited, its just that Nim is suited much better.

I found Nim to not only satisfy the requirements for writing a kernel (which Rust also does) but also I can actually get how the whole thing works. I attribute it primarily to the fact that it generates "readable" C code as its target. 

I can elaborate if you are interested.

**Comment by mkpankov** [comment]
Yeah, some details would be nice!

I'm considering using a modern language for systems programming and would like an opinion of experienced developer.

**Comment by ckkashyap** [comment]
From a feature set point of view I believe Rust and Nim are
almost at par. A couple of aspects of Nim give it an edge in my
opinion.
1. The module system of Nim is simple (in my opinion, it takes
   more work to make something simple). Since Nim transforms each
   Nim file into a corresponding C file, it's really easy to see
   what's happening under the hood. In case of Rust, I'd need to
   invest more time to understand it's module system.
2. Since C is the target, it gives me freedom to write code for
   any platform I like - without having to wait for the language
   maintainers. (Rust targets llvm which is dependent on C++ so
   reaching arbitrary platforms is not going to be pleasant)

This link has some more comparison data - 
https://github.com/andreaferretti/on-rust-and-nim

You can take a look at the my xv6 source in Nim - I was able to make progress much faster in Nim.

**Comment by justgage** [comment]
Thanks for showing me nim. Didn't even know it existed!

**Comment by ghost** [comment]
It's named nimrod before, a long name , can not easily remember. but now, it named nim.
A short and easily remember word.
Like it renamed to nim. wise choice.

**Comment by ckkashyap** [comment]
http://ckkashyap.blogspot.in/2015/02/nim-is-best-programming-language.html
